CREATE TABLE IF NOT EXISTS rooms(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_by INT REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);